### ISSUE TITLE
cannot get mac address

### ISSUE THREAD

**Issue by MikeZhou** [QbsuranAlang/iOSGetMACAddress#1]
hello,
    I cannot use your demo get mac address after ios10， if you have any other way?

thanks

**Comment by QbsuranAlang** [comment]
are you connected to any wi-fi?
please show more detail.

**Comment by MikeZhou** [comment]
yes,I connected to wifi! but the value is 02:00:00:00:00:00!

I can get the right mac address in ios9!
![img_0307](https://cloud.githubusercontent.com/assets/3191463/23848623/1c949f24-0813-11e7-8a39-77cfba913f35.PNG)

**Comment by QbsuranAlang** [comment]
problem solved.
thanks for your information.
and BTW.
我會說中文
