### ISSUE TITLE
res_search failed

### ISSUE THREAD

**Issue by MikeZhou** [QbsuranAlang/iOSGetMACAddress#2]
哈啰：
      when I run in ios10.2.1,it tell me that "res_search failed"! how can I resolve it? 

谢谢！

<img width="641" alt="2017-03-14 09 30 10" src="https://cloud.githubusercontent.com/assets/3191463/23882027/10f51c9e-0899-11e7-8db9-937374dd5d0d.png">

**Comment by QbsuranAlang** [comment]
Hello
I add third way to get mac address.
But I still don't know what cause your problem.
I am already add some error output.
Please give me your error message, if you can.

**Comment by QbsuranAlang** [comment]
BTW, the third way didn't work on iOS 10.3

**Comment by MikeZhou** [comment]
way2 is OK，but way3 is still not function,thanks!

error info:
"res_search(): Host name lookup failure"

![img_0308](https://cloud.githubusercontent.com/assets/3191463/23929577/356b9818-0962-11e7-95bb-54ba50083b54.PNG)

**Comment by QbsuranAlang** [comment]
I got it.
Way3 is query "_apple-mobdev2._tcp.local" using mDNS(like DNS) to self, the response will be formatted: mac_address@ipv6_address.
Actually I am not sure what bonjour service it is, maybe my device enable something.
These ways are proof of my concept.
